// Generated by Selenium IDE
using System.Collections.Generic;
using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Firefox;

[TestFixture]
public class AuthorizationTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void Authorization() {
    driver.Navigate().GoToUrl("https://www.lastpass.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1295, 695);
    driver.FindElement(By.CssSelector(".cdlogin h3")).Click();
    driver.FindElement(By.CssSelector(".css-i9gxme .css-1qv22w3")).SendKeys("sagadeev.artem2001@gmail.com");
    driver.FindElement(By.CssSelector(".css-79elbk .css-1qv22w3")).Click();
    driver.FindElement(By.CssSelector(".css-79elbk .css-1qv22w3")).SendKeys("Wepob19862001");
    driver.FindElement(By.CssSelector(".css-7y6612")).Click();
  }
}
