// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class NoteCreatingTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new FirefoxDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void noteCreating() {
    driver.Navigate().GoToUrl("https://www.lastpass.com/");
    driver.FindElement(By.CssSelector(".cdlogin h3")).Click();
    driver.FindElement(By.CssSelector(".css-i9gxme .css-1qv22w3")).SendKeys("sagadeev.artem2001@gmail.com");
    driver.FindElement(By.CssSelector(".css-79elbk .css-1qv22w3")).Click();
    driver.FindElement(By.CssSelector(".css-79elbk .css-1qv22w3")).SendKeys("Wepob19862001");
    driver.FindElement(By.CssSelector(".css-7y6612")).Click();
    
    driver.Manage().Timeouts().ImplicitWait = TimeSpan.FromSeconds(15);
    //driver.SwitchTo().Frame(0);

    var frame = driver.FindElement(By.CssSelector("#newvault"));
    driver.SwitchTo().Frame(frame);
    driver.FindElement(By.CssSelector("#addMenuButton")).Click();
    driver.FindElement(By.CssSelector("#addMenuButtonCustom .focusable-add-menu-item")).Click();
    driver.FindElement(By.CssSelector(".SecureNote")).Click();
    driver.FindElement(By.CssSelector("div:nth-child(1) > div > .dialogInput")).Click();
    driver.FindElement(By.CssSelector("div:nth-child(1) > div > .dialogInput")).SendKeys("New note");
    driver.FindElement(By.CssSelector("td > .dialogInput")).Click();
    driver.FindElement(By.CssSelector("td > .dialogInput")).SendKeys("Content of the note");
    driver.FindElement(By.CssSelector(".rbtn:nth-child(3)")).Click();
  }
}
